name: Bug Report
description: Report broken or incorrect behaviour
labels: unconfirmed bug
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out a bug.

        Please note that this form is for bugs only!
  - type: input
    attributes:
      label: Summary
      description: A simple summary of your bug report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
         What you did to make it happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: >
        What actually happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin Version
      description: ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Flow Launcher Version
      description: Go into your flow launcher settings, go into the about section, and the version should be at the top.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Python Version/Path
      description: Go into your flow launcher settings, go to the general section, and scroll down until you find the `Python Path` field. Copy and paste the value here.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure you've properly done due diligence when reporting this issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true
        - label: I have removed my token from display, if visible.
          required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
